gradient_accumulation_steps: 1  
learning_rate:  0.001
warmup_steps: 500
max_steps: 20
gradient_checkpointing: True
fp16: True
per_device_eval_batch_size: 8
predict_with_generate: True
generation_max_length: 225
save_steps: 1000
eval_steps: 1000
logging_steps: 25
report_to: ["tensorboard"]
load_best_model_at_end: True
metric_for_best_model: "wer"